"""create explanation table

Revision ID: 42021d635d54
Revises: b308a8d5be55
Create Date: 2026-10-04 19:32:38.418603

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "42021d635d54"
down_revision: str | Sequence[str] | None = "b308a8d5be55"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "explanation",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("concept_id", sa.Integer(), nullable=False),
        sa.Column("answer_id", sa.Integer(), nullable=False),
        sa.Column("key_idea_ids", sa.JSON(), nullable=False),
        sa.Column(
            "angle",
            sa.Enum(
                "analogy",
                "example",
                "step_by_step",
                name="explanationangle",
                native_enum=False,
                length=32,
            ),
            nullable=False,
        ),
        sa.Column("text", sa.Text(), nullable=False),
        sa.Column("source_chunk_ids", sa.JSON(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["answer_id"], ["answer.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["concept_id"], ["concept.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["user_id"], ["user.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("answer_id"),
    )
    op.create_index(op.f("ix_explanation_concept_id"), "explanation", ["concept_id"], unique=False)
    op.create_index(op.f("ix_explanation_user_id"), "explanation", ["user_id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_explanation_user_id"), table_name="explanation")
    op.drop_index(op.f("ix_explanation_concept_id"), table_name="explanation")
    op.drop_table("explanation")
    # ### end Alembic commands ###
