"""create user table

Revision ID: 8ea417798f4e
Revises:
Create Date: 2026-10-04 14:54:11.273864

"""

from collections.abc import Sequence

import sqlalchemy as sa
import sqlmodel
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "8ea417798f4e"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "user",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###

    # The single default user (DEFAULT_USER_ID) until real accounts exist.
    op.execute("""INSERT INTO "user" (id, name) VALUES (1, 'default')""")
    op.execute("""SELECT setval(pg_get_serial_sequence('"user"', 'id'), 1)""")


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("user")
    # ### end Alembic commands ###
