"""create learning session tables

Revision ID: b308a8d5be55
Revises: de9cefa2dbf6
Create Date: 2026-10-04 18:58:53.379696

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "b308a8d5be55"
down_revision: str | Sequence[str] | None = "de9cefa2dbf6"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "learnerconceptstate",
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("concept_id", sa.Integer(), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "untouched",
                "in_progress",
                "mastered",
                name="conceptstatus",
                native_enum=False,
                length=32,
            ),
            nullable=False,
        ),
        sa.Column("mastery", sa.Float(), nullable=False),
        sa.Column("mastered_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("last_seen", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["concept_id"], ["concept.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["user_id"], ["user.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("user_id", "concept_id"),
    )
    op.create_index(
        op.f("ix_learnerconceptstate_concept_id"),
        "learnerconceptstate",
        ["concept_id"],
        unique=False,
    )
    op.create_table(
        "question",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("concept_id", sa.Integer(), nullable=False),
        sa.Column("position", sa.Integer(), nullable=False),
        sa.Column("text", sa.Text(), nullable=False),
        sa.Column(
            "level",
            sa.Enum("explain", "apply", name="questionlevel", native_enum=False, length=32),
            nullable=False,
        ),
        sa.Column("tested_key_idea_ids", sa.JSON(), nullable=False),
        sa.Column("source_chunk_ids", sa.JSON(), nullable=False),
        sa.Column(
            "origin",
            sa.Enum("plan", "follow_up", name="questionorigin", native_enum=False, length=32),
            nullable=False,
        ),
        sa.Column(
            "state",
            sa.Enum(
                "planned", "asked", "answered", name="questionstate", native_enum=False, length=32
            ),
            nullable=False,
        ),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["concept_id"], ["concept.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["user_id"], ["user.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_question_concept_id"), "question", ["concept_id"], unique=False)
    op.create_index(op.f("ix_question_user_id"), "question", ["user_id"], unique=False)
    op.create_table(
        "answer",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("question_id", sa.Integer(), nullable=False),
        sa.Column("text", sa.Text(), nullable=False),
        sa.Column("evaluation", sa.JSON(none_as_null=True), nullable=True),
        sa.Column("dispute_reason", sa.Text(), nullable=True),
        sa.Column("regraded", sa.Boolean(), nullable=False),
        sa.Column("points_possible", sa.Float(), nullable=False),
        sa.Column("points_earned", sa.Float(), nullable=True),
        sa.Column("score", sa.Float(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["question_id"], ["question.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("question_id"),
    )
    op.create_table(
        "learnerkeyideastate",
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("key_idea_id", sa.Integer(), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "untested",
                "correct",
                "partial",
                "missing",
                "misconception",
                name="keyideastatus",
                native_enum=False,
                length=32,
            ),
            nullable=False,
        ),
        sa.Column("failed_attempts", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(["key_idea_id"], ["keyidea.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["user_id"], ["user.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("user_id", "key_idea_id"),
    )
    op.create_index(
        op.f("ix_learnerkeyideastate_key_idea_id"),
        "learnerkeyideastate",
        ["key_idea_id"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_learnerkeyideastate_key_idea_id"), table_name="learnerkeyideastate")
    op.drop_table("learnerkeyideastate")
    op.drop_table("answer")
    op.drop_index(op.f("ix_question_user_id"), table_name="question")
    op.drop_index(op.f("ix_question_concept_id"), table_name="question")
    op.drop_table("question")
    op.drop_index(op.f("ix_learnerconceptstate_concept_id"), table_name="learnerconceptstate")
    op.drop_table("learnerconceptstate")
    # ### end Alembic commands ###
