"""create concept graph and llm call tables

Revision ID: de9cefa2dbf6
Revises: 52c7e8c962fe
Create Date: 2026-10-04 18:39:24.266752

"""

from collections.abc import Sequence

import sqlalchemy as sa
import sqlmodel
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "de9cefa2dbf6"
down_revision: str | Sequence[str] | None = "52c7e8c962fe"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "concept",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("document_id", sa.Integer(), nullable=False),
        sa.Column("position", sa.Integer(), nullable=False),
        sa.Column("name", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("definition", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("source_chunk_ids", sa.JSON(), nullable=False),
        sa.ForeignKeyConstraint(["document_id"], ["document.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_concept_document_id"), "concept", ["document_id"], unique=False)
    op.create_table(
        "llmcall",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("document_id", sa.Integer(), nullable=True),
        sa.Column(
            "purpose",
            sa.Enum("concept_extraction", name="llmpurpose", native_enum=False, length=32),
            nullable=False,
        ),
        sa.Column("model", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("input_tokens", sa.Integer(), nullable=False),
        sa.Column("output_tokens", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["document_id"], ["document.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["user_id"], ["user.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_llmcall_created_at"), "llmcall", ["created_at"], unique=False)
    op.create_index(op.f("ix_llmcall_document_id"), "llmcall", ["document_id"], unique=False)
    op.create_index(op.f("ix_llmcall_user_id"), "llmcall", ["user_id"], unique=False)
    op.create_table(
        "keyidea",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("concept_id", sa.Integer(), nullable=False),
        sa.Column("position", sa.Integer(), nullable=False),
        sa.Column("text", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.ForeignKeyConstraint(["concept_id"], ["concept.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_keyidea_concept_id"), "keyidea", ["concept_id"], unique=False)
    op.create_table(
        "prerequisiteedge",
        sa.Column("from_concept_id", sa.Integer(), nullable=False),
        sa.Column("to_concept_id", sa.Integer(), nullable=False),
        sa.Column("confidence", sa.Float(), nullable=False),
        sa.ForeignKeyConstraint(["from_concept_id"], ["concept.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["to_concept_id"], ["concept.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("from_concept_id", "to_concept_id"),
    )
    op.create_index(
        op.f("ix_prerequisiteedge_to_concept_id"),
        "prerequisiteedge",
        ["to_concept_id"],
        unique=False,
    )
    # ### end Alembic commands ###

    # Documents processed before concept extraction existed have no graph; a retry builds it.
    op.execute(
        "UPDATE document SET status = 'failed', step = 'extracting_concepts', "
        "error_message = 'This document has no concept graph yet. Retry to build it.' "
        "WHERE status = 'ready'"
    )


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_prerequisiteedge_to_concept_id"), table_name="prerequisiteedge")
    op.drop_table("prerequisiteedge")
    op.drop_index(op.f("ix_keyidea_concept_id"), table_name="keyidea")
    op.drop_table("keyidea")
    op.drop_index(op.f("ix_llmcall_user_id"), table_name="llmcall")
    op.drop_index(op.f("ix_llmcall_document_id"), table_name="llmcall")
    op.drop_index(op.f("ix_llmcall_created_at"), table_name="llmcall")
    op.drop_table("llmcall")
    op.drop_index(op.f("ix_concept_document_id"), table_name="concept")
    op.drop_table("concept")
    # ### end Alembic commands ###
